ALTER TABLE carts ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE cart_items ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE orders ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE order_items ADD COLUMN version BIGINT DEFAULT 0;