



CREATE TABLE contact_addresses
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    profile_id     BIGINT                                  NOT NULL,
    recipient_name VARCHAR(50)                             NOT NULL,
    phone_number   VARCHAR(15)                             NOT NULL,
    province_code  VARCHAR(20)                             NOT NULL,
    province_name  VARCHAR(255)                            NOT NULL,
    ward_code      VARCHAR(20)                             NOT NULL,
    ward_name      VARCHAR(255)                            NOT NULL,
    district_name  VARCHAR(255)                            NOT NULL,
    detail_address VARCHAR(255)                            NOT NULL,
    is_default     BOOLEAN                                 NOT NULL,
    notes          VARCHAR(255),
    CONSTRAINT pk_contact_addresses PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked     BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    name        VARCHAR(30)                             NOT NULL,
    description TEXT                                    NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_profiles
(
    user_id    BIGINT       NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    full_name  VARCHAR(100) NOT NULL,
    phone      VARCHAR(20),
    avatar_url VARCHAR(255),
    birth_date date,
    gender     VARCHAR(10),
    CONSTRAINT pk_user_profiles PRIMARY KEY (user_id)
);

CREATE TABLE users
(
    id          BIGINT       NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    username    VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    provider    VARCHAR(20),
    provider_id VARCHAR(255),
    status      VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id    BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_refresh_token_expiry ON refresh_tokens (expiry_date);

ALTER TABLE contact_addresses
    ADD CONSTRAINT FK_CONTACT_ADDRESSES_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES user_profiles (user_id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT FK_USERS_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT FK_USERS_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);