CREATE TABLE arrangement_styles
(
    id             BIGINT       NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    name           VARCHAR(100) NOT NULL,
    description    TEXT,
    image_url      VARCHAR(255),
    base_labor_fee DECIMAL(15, 2),
    CONSTRAINT pk_arrangement_styles PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id          BIGINT       NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(250) NOT NULL,
    description TEXT,
    parent_id   BIGINT,
    type        VARCHAR(20),
    is_active   BOOLEAN      NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE inventory_transactions
(
    id             BIGINT      NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    material_id    BIGINT      NOT NULL,
    change_amount  INTEGER     NOT NULL,
    reference_code VARCHAR(255),
    type           VARCHAR(20) NOT NULL,
    CONSTRAINT pk_inventory_transactions PRIMARY KEY (id)
);

CREATE TABLE material_stocks
(
    id                BIGINT  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    quantity          INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    opening_balance   INTEGER NOT NULL,
    reorder_level     INTEGER DEFAULT 10,
    CONSTRAINT pk_material_stocks PRIMARY KEY (id)
);

CREATE TABLE materials
(
    id            BIGINT       NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    name          VARCHAR(255) NOT NULL,
    unit          VARCHAR(255) NOT NULL,
    image_url     VARCHAR(255),
    cost_price    DECIMAL(15, 2),
    selling_price DECIMAL(15, 2),
    type          VARCHAR(20),
    CONSTRAINT pk_materials PRIMARY KEY (id)
);

CREATE TABLE product_assets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    url          VARCHAR(255)                            NOT NULL,
    public_id    VARCHAR(255),
    type         VARCHAR(255)                            NOT NULL,
    is_thumbnail BOOLEAN,
    position     INTEGER,
    meta_data    JSONB,
    product_id   BIGINT,
    CONSTRAINT pk_product_assets PRIMARY KEY (id)
);

CREATE TABLE product_categories
(
    category_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL
);

CREATE TABLE product_recipes
(
    id              BIGINT  NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    product_id      BIGINT  NOT NULL,
    material_id     BIGINT  NOT NULL,
    quantity_needed INTEGER NOT NULL,
    CONSTRAINT pk_product_recipes PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                   BIGINT         NOT NULL,
    deleted_at           TIMESTAMP WITHOUT TIME ZONE,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    created_by           VARCHAR(255),
    updated_by           VARCHAR(255),
    name                 VARCHAR(200)   NOT NULL,
    description          TEXT,
    thumbnail            VARCHAR(500),
    slug                 VARCHAR(250)   NOT NULL,
    prepared_quantity    INTEGER,
    is_make_to_order     BOOLEAN,
    base_price           DECIMAL(15, 2) NOT NULL,
    status               VARCHAR(20)    NOT NULL,
    arrangement_style_id BIGINT,
    average_rating       DOUBLE PRECISION,
    review_count         INTEGER,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_slug UNIQUE (slug);

ALTER TABLE products
    ADD CONSTRAINT uc_products_slug UNIQUE (slug);

ALTER TABLE product_recipes
    ADD CONSTRAINT unique_constraint_product_recipe UNIQUE (product_id, material_id);

CREATE INDEX idx_category_name ON categories (name);

CREATE INDEX idx_category_slug ON categories (slug);

CREATE INDEX idx_product_name ON products (name);

CREATE INDEX idx_product_slug ON products (slug);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);

ALTER TABLE inventory_transactions
    ADD CONSTRAINT FK_INVENTORY_TRANSACTIONS_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES materials (id);

ALTER TABLE material_stocks
    ADD CONSTRAINT FK_MATERIAL_STOCKS_ON_ID FOREIGN KEY (id) REFERENCES materials (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_ARRANGEMENT_STYLE FOREIGN KEY (arrangement_style_id) REFERENCES arrangement_styles (id);

ALTER TABLE product_assets
    ADD CONSTRAINT FK_PRODUCT_ASSETS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_recipes
    ADD CONSTRAINT FK_PRODUCT_RECIPES_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES materials (id);

ALTER TABLE product_recipes
    ADD CONSTRAINT FK_PRODUCT_RECIPES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_categories
    ADD CONSTRAINT fk_procat_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE product_categories
    ADD CONSTRAINT fk_procat_on_product FOREIGN KEY (product_id) REFERENCES products (id);

